/**
 * How to Play — Scannable guide written for beginners.
 * Includes detective framing, 5 suspects with live-rendered light curves,
 * competition format, interaction guide, and scoring overview.
 */

import { useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { generateCurve, type CurveType } from '../lib/lightcurve';
import { MiniCurveRenderer } from '../components/MiniCurveRenderer';

interface SuspectInfo {
  type: CurveType;
  name: string;
  signature: string;
  details: string;
  seed: number;
  marginal?: boolean;
}

const SUSPECTS: SuspectInfo[] = [
  {
    type: 'planet',
    name: 'Planet Transit',
    signature: 'Shallow dip (0.1%–3%), flat bottom, repeats on a strict period',
    details:
      'When an exoplanet passes between us and its host star, it blocks a tiny fraction of starlight. The dip is shallow, flat at the bottom during full transit, and repeats periodically.',
    seed: 101,
  },
  {
    type: 'eclipsingBinary',
    name: 'Eclipsing Binary',
    signature: 'Deep (5%–30%), V-shaped, alternating deep/shallow dips',
    details:
      'Two stars orbiting each other. As the smaller/fainter star passes in front of the primary star (or vice-versa), deep V-shaped dips occur. Odd transits are typically 10–20% deeper than even ones!',
    seed: 202,
  },
  {
    type: 'stellarVariability',
    name: 'Stellar Variability',
    signature: 'Smooth wandering brightness, no sharp dips, no strict period',
    details:
      'Starspots, stellar pulsation, or rotation cause continuous, smooth fluctuations in brightness over days or weeks without distinct transit shapes.',
    seed: 303,
  },
  {
    type: 'instrumentNoise',
    name: 'Instrument Noise',
    signature: 'Random scatter and spikes, nothing repeats',
    details:
      'Telescope jitter, cosmic ray hits, or detector artifacts create random Gaussian noise and sharp single-point spikes. No periodic pattern exists.',
    seed: 404,
  },
  {
    type: 'insufficientData',
    name: 'Insufficient Data',
    signature: 'One dip only, never observed again',
    details:
      'A single candidate dip is recorded, but the observation ends before a second transit could occur. Without periodicity, a planet cannot be confirmed.',
    seed: 505,
  },
];

export default function HowToPlay() {
  const navigate = useNavigate();

  const renderedSuspects = useMemo(() => {
    return SUSPECTS.map((s) => ({
      ...s,
      curve: generateCurve(s.type, s.seed, 'medium'),
    }));
  }, []);

  return (
    <div className="min-h-screen bg-void py-8 px-6">
      <div className="max-w-5xl mx-auto space-y-10">
        {/* Header / Detective Framing */}
        <div className="bg-panel border border-border rounded-xl p-8 text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 p-8 opacity-10 font-mono text-8xl select-none text-accent">
            🕵️‍♂️
          </div>
          <span className="text-xs text-accent font-semibold uppercase tracking-[0.25em] block mb-2">
            Astronomical Detective Guide
          </span>
          <h1 className="text-3xl font-bold text-bright mb-4">
            How Exoplanet Watch Works
          </h1>
          <p className="text-subtle text-base max-w-2xl mx-auto leading-relaxed">
            You play an astronomer investigating starlight. The suspect is a distant star. Your primary evidence is a <strong className="text-text">light curve</strong> — a graph measuring stellar brightness over time. When something passes in front of the star, brightness dips. Your job: figure out <em className="text-bright font-normal">what caused the dip.</em>
          </p>
        </div>

        {/* The 5 Suspects Table */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold text-bright flex items-center gap-2">
              <span>🔍</span> The Five Suspects
            </h2>
            <span className="text-xs text-muted">
              Live light curves generated by the competition engine
            </span>
          </div>

          <div className="space-y-6">
            {renderedSuspects.map((suspect) => (
              <div
                key={suspect.type}
                className="bg-panel border border-border rounded-xl p-5 grid grid-cols-1 lg:grid-cols-[1fr_420px] gap-6 items-center"
              >
                <div>
                  <div className="flex items-center gap-3 mb-2">
                    <h3 className="text-lg font-semibold text-bright">
                      {suspect.name}
                    </h3>
                    <span className="text-xs font-mono px-2 py-0.5 rounded bg-surface border border-border text-accent">
                      {suspect.curve.truth.correctAnswer}
                    </span>
                  </div>
                  <div className="text-sm text-transit-mark font-medium mb-3">
                    {suspect.signature}
                  </div>
                  <p className="text-sm text-subtle leading-relaxed">
                    {suspect.details}
                  </p>
                </div>
                <div className="bg-surface/50 p-2 rounded-lg border border-border/50 flex justify-center">
                  <MiniCurveRenderer
                    points={suspect.curve.points}
                    width={400}
                    height={160}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Game Rules & Scoring Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-panel border border-border rounded-xl p-6">
            <div className="text-2xl mb-2">👥</div>
            <h3 className="text-base font-semibold text-bright mb-2">
              Team & Structure
            </h3>
            <p className="text-xs text-subtle leading-relaxed">
              Play in teams of 2 over 4 rounds of increasing difficulty.
              Everything runs client-side in your browser. All observations are generated deterministically for your team.
            </p>
          </div>

          <div className="bg-panel border border-border rounded-xl p-6">
            <div className="text-2xl mb-2">🖱️</div>
            <h3 className="text-base font-semibold text-bright mb-2">
              Interactive Answers
            </h3>
            <p className="text-xs text-subtle leading-relaxed">
              Answers come from plot interaction! Click dips to mark transit times, drag vertical markers to bracket durations, and drag horizontal lines to measure depth directly.
            </p>
          </div>

          <div className="bg-panel border border-border rounded-xl p-6">
            <div className="text-2xl mb-2">⚖️</div>
            <h3 className="text-base font-semibold text-bright mb-2">
              Scoring Strategy
            </h3>
            <p className="text-xs text-subtle leading-relaxed">
              Reasoning matters more as you advance. Accuracy and precise measurement are auto-scored instantly, while written justification is reviewed by competition judges.
            </p>
          </div>
        </div>

        {/* Navigation Action */}
        <div className="flex justify-center gap-4 pt-4">
          <button
            onClick={() => navigate('/tutorial')}
            className="px-6 py-3 bg-surface border border-accent/60 text-bright rounded-lg hover:bg-accent/10 transition-colors font-medium text-sm flex items-center gap-2"
          >
            🎬 Watch Animated Walkthrough
          </button>
          <button
            onClick={() => navigate('/handbook')}
            className="px-6 py-3 bg-surface border border-border text-text rounded-lg hover:border-accent transition-colors font-medium text-sm"
          >
            📖 Read Mission Handbook
          </button>
          <button
            onClick={() => navigate('/setup')}
            className="px-8 py-3 bg-accent text-white font-semibold rounded-lg hover:bg-accent-glow transition-all text-sm"
          >
            Start Mission →
          </button>
        </div>
      </div>
    </div>
  );
}
